{{- if and .Values.config.secretEnv (not .Values.config.existingSecretName) }}
{{- $secretName := default (printf "%s-secret" (include "orders-worker.fullname" .)) .Values.config.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "orders-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.config.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
