{{- if .Values.config.env }}
{{- $configMapName := default (printf "%s-env" (include "orders-api.fullname" .)) .Values.config.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
